# Generated by Django 3.1.7 on 2021-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0004_auto_20210222_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='Product Description', max_length=140),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='349543', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
