# Generated by Django 3.1.7 on 2021-02-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0005_auto_20210222_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='750259', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
