# Generated by Django 3.1.7 on 2021-02-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0006_auto_20210224_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='829215', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
