# Generated by Django 3.1.5 on 2021-02-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0008_auto_20210224_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='859816', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
