# Generated by Django 3.1.7 on 2021-02-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0009_auto_20210224_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='327574', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
