# Generated by Django 3.1.7 on 2021-02-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0018_auto_20210224_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='someEmail', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='155612', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
