# Generated by Django 3.1.7 on 2021-02-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0019_auto_20210226_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(blank=True, default='379023', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='913586', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
