# Generated by Django 3.1.7 on 2021-02-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0020_auto_20210226_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(blank=True, default='175007', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='510739', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
