# Generated by Django 3.1.5 on 2021-02-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0021_auto_20210226_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(blank=True, default='933704', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='647840', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
