# Generated by Django 3.1.5 on 2021-02-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0023_auto_20210226_0503'),
        ('chinesseRestaurant', '0023_auto_20210226_2040'),
    ]

    operations = [
    ]
