# Generated by Django 3.1.7 on 2021-02-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0023_auto_20210226_2040'),
        ('chinesseRestaurant', '0024_auto_20210226_1440'),
    ]

    operations = [
    ]
