# Generated by Django 3.1.5 on 2021-02-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0024_merge_20210226_2045'),
        ('chinesseRestaurant', '0024_auto_20210226_1440'),
    ]

    operations = [
    ]
