# Generated by Django 3.1.7 on 2021-03-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0025_merge_20210226_2051'),
        ('chinesseRestaurant', '0025_merge_20210226_2106'),
    ]

    operations = [
    ]
