# Generated by Django 3.1.7 on 2021-03-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0026_merge_20210303_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(blank=True, default='212200', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='617816', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
