# Generated by Django 3.1.7 on 2021-03-03 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chinesseRestaurant', '0027_auto_20210303_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(blank=True, default='785179', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='369054', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
