# Generated by Django 3.1.7 on 2021-03-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0029_auto_20210303_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='611555', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
