# Generated by Django 3.1.7 on 2021-03-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0030_auto_20210304_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='663848', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
