# Generated by Django 3.1.7 on 2021-03-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesseRestaurant', '0033_auto_20210304_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=True, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='streetNum',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(default=True, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(blank=True, default='173037', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
